.XXXXX.........
XX.XXXX........
....X.XX.....XX
..XX.X.XX..XXX.
.XXX....X.XXXX.
.XXXX...XX.XX..
.XX..X.XXXXX...
..XX.X.XXXXXXXX
.....XX.XXXXXX.
......XX...XX..
.......XXXX.XX.
........X.XXXX.
......XX...X.XX
.XXXXXXXXX.X.XX
...XX.XX...XX.X
...XX.XX...XXXX
..XXXXXXX...X.X
...XX.XX....XXX
..XXX.XXX....XX
XXXXXXXXXXX...X
