............X.
............X.
...........XX.
XXX.......XX..
..XXX.....XXX.
...XXX.....XXX
....XXX.....XX
.....XX.....X.
.....XXX......
.....XXX.XXXX.
......XXXXXXXX
......XXXXX.XX
.......XXX..X.
........XXXX..
